### ISSUE TITLE
The module run into a internal server error

### ISSUE THREAD

**Issue by WebCrew** [jeremiahtenbrink/HumhubCertifiedRealModule#1]
Hi,

 I installed your module, but if I click the **settings link in HumHubs admin backend sidebar** then I run into a **internal server error**. 

**Check the screenshot please:** 

![certified](https://cloud.githubusercontent.com/assets/12986067/22696816/ca2ba404-ed4f-11e6-913f-1c0086527e6d.png)

**And here is the error lof file:**

Tue, 07 Feb 2017 16:06:58 +0100  yii\base\UnknownPropertyException
yii\base\UnknownPropertyException: Getting unknown property: humhub\modules\certified\models\AwaitingCertification::her_picture_url in /var/www/web917/html/todgmbh/cms/protected/vendor/yiisoft/yii2/base/Component.php:143 Stack trace: #0 /var/www/web917/html/todgmbh/cms/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(286): yii\base\Component->__get('her_picture_url') #1 /var/www/web917/html/todgmbh/cms/protected/vendor/yiisoft/yii2/validators/Validator.php(262): yii\db\BaseActiveRecord->__get('her_picture_url') #2 /var/www/web917/html/todgmbh/cms/protected/vendor/yiisoft/yii2/base/Model.php(356): yii\validators\Validator->validateAttributes(Object(humhub\modules\certified\models\AwaitingCertification), Array) #3 /var/www/web917/html/todgmbh/cms/protected/modules/certified/models/AwaitingCertification.php(70): yii\base\Model->validate() #4 /var/www/web917/html/todgmbh/cms/protected/modules/certified/controllers/AdminController.php(39): humhub\modules\certified\models\AwaitingCertification->search(Array) #5 [internal function]: humhub\modules\certified\controllers\AdminController->actionIndex() #6 /var/www/web917/html/todgmbh/cms/protected/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array) #7 /var/www/web917/html/todgmbh/cms/protected/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams(Array) #8 /var/www/web917/html/todgmbh/cms/protected/vendor/yiisoft/yii2/base/Module.php(454): yii\base\Controller->runAction('', Array) #9 /var/www/web917/html/todgmbh/cms/protected/vendor/yiisoft/yii2/web/Application.php(100): yii\base\Module->runAction('certified/admin', Array) #10 /var/www/web917/html/todgmbh/cms/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(humhub\components\Request)) #11 /var/www/web917/html/todgmbh/cms/index.php(25): yii\base\Application->run() #12 {main}

**Comment by jeremiahtenbrink** [comment]
this issue is fixed with the new update.
